dataroot: "./archive/"
image_path: 'train_images'
mask_path: 'train_masks'
data_dim:
  width: 256
  height: 256
split_ratio: 0.8
batch_size: 4
epochs: 5
U-net:
  in_channels: 3
  out_channels: 1
  encoder: #output channels for each layer 
    E1: 64
    E2: 128
    E3: 256
    E4: 512
  bottleneck: 1024
  decoder:
    D1: 512
    D2: 256
    D3: 128
    D4: 64
  

Train_step: 
  lr: 0.01
  device: "cuda" # "cpu" or "cuda"
  criterion: "BCEWithLogitsLoss" # "BCEWithLogitsLoss" or "DiceLoss"
  optimizer: "Adam" # "Adam" or "SGD"